[build]
# command = "npm run build"
functions = "functions"
# publish="dist"

[[redirects]]
  from = "/"
  to = "/dist"

[[redirects]]
  from = "/api/*"
  to="/.netlify/functions/:splat"

  [functions]
  # Specifies `esbuild` for functions bundling
  node_bundler = "esbuild"
  external_node_modules = ["node_modules"]